/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.jcu.prf.volby;

import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.Arrays;
import java.util.Enumeration;
import java.util.List;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author User
 * 
 */
public class ElectionWindow extends javax.swing.JFrame {

    
    private int height = 12;
    private List<Candidate> candi;
    private ButtonGroup candiGroup = new ButtonGroup();
    
    Person loggedPerson;
    LoginWindow lw;
    ElectionService esm;
    private ElectionDao ed = ElectionDaoImplementaion.getInstance();
    /**
     * Creates new form ElectionWindow
     */
    public ElectionWindow(LoginWindow lw) {
        initComponents();
        if (lw!=null)
            this.lw = lw;
        esm = new ElectionServiceImplementation();
        
         addWindowListener(exitListener); //REGISTER LISTENER
         
         candi = esm.getCanditates();
         //Populate logged person
         String[] personParam = ed.getPerson(lw.loginField().getText());
         loggedPerson = new Person(Integer.parseInt(personParam[0]), personParam[1], personParam[2], 0);
         //set login user
         nameLabel.setText(loggedPerson.getName());
         surnameLabel.setText(loggedPerson.getSurname());
         
         generateRadioButtons();
         
    }
    
    WindowListener exitListener = new WindowAdapter() {

    @Override
    public void windowClosing(WindowEvent e) {
        //Zavře okno
        dispose();
    }
};
    
    public void generateRadioButtons()
    {
        Font  f1  = new Font(Font.SERIF, Font.PLAIN,  14);
        for(int i = 0; i < candi.size(); i++)
        {
            JRadioButton button1 = new JRadioButton(candi.get(i).getFullName());
            button1.setName(Long.toString(candi.get(i).getID()));
            button1.setSize(300, 20);
            button1.setFont(f1);
            button1.setLocation(5 ,height );
            height = height + 30;
            candiPanel.add(button1);
            
            candiGroup.add(button1);
            //System.out.println(candi.get(i).getName());
            
        }
      
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoutButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        surnameLabel = new javax.swing.JLabel();
        voteButton = new javax.swing.JButton();
        candiPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Volební okno");
        setResizable(false);

        logoutButton.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        logoutButton.setText("Odhlásit");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameLabel.setText("jLabel1");
        nameLabel.setMaximumSize(new java.awt.Dimension(43, 16));
        nameLabel.setMinimumSize(new java.awt.Dimension(43, 16));
        nameLabel.setPreferredSize(new java.awt.Dimension(43, 16));

        surnameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        surnameLabel.setText("jLabel2");
        surnameLabel.setMaximumSize(new java.awt.Dimension(43, 16));
        surnameLabel.setMinimumSize(new java.awt.Dimension(43, 16));
        surnameLabel.setPreferredSize(new java.awt.Dimension(43, 16));

        voteButton.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        voteButton.setText("Hlasovat");
        voteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout candiPanelLayout = new javax.swing.GroupLayout(candiPanel);
        candiPanel.setLayout(candiPanelLayout);
        candiPanelLayout.setHorizontalGroup(
            candiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );
        candiPanelLayout.setVerticalGroup(
            candiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(candiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(surnameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(voteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(185, 185, 185))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(surnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(candiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22)
                .addComponent(voteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        LoginWindow lw = new LoginWindow(esm);
        lw.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void voteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voteButtonActionPerformed
        // projít všechny prvky ve skupině voličů (zaškrtávátek)
        for (Enumeration<AbstractButton> buttons = candiGroup.getElements(); buttons.hasMoreElements();) {
            // přiřadit tlačítko
            AbstractButton button = buttons.nextElement();
            // pokud je nějaký volič vybraný, toho chceme volit
            if (button.isSelected()) {
                try {
                    // pomocí tlačítka si vrať ID vybraného kandidáta
                    esm.vote(loggedPerson.getID(), Long.parseLong(button.getName()));
                    // zobraz okno o potvrzení
                    JOptionPane.showMessageDialog(this, "Váš hlas byl odevzdán!", "Odevzdáno", JOptionPane.DEFAULT_OPTION);
                    return;
                } catch (DuplicateVoteException ex) {
                    JOptionPane.showMessageDialog(this, "Už jste hlasovali!", "Varování", JOptionPane.WARNING_MESSAGE);
                    return;
                } catch (NotFoundException ex) {
                    JOptionPane.showMessageDialog(this, "Vybraná osoba nebyla naleznuta", "Varování", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
        }
        JOptionPane.showMessageDialog(this, "Nikdo nebyl zvolen", "Varování", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_voteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel candiPanel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel surnameLabel;
    private javax.swing.JButton voteButton;
    // End of variables declaration//GEN-END:variables
}
